- README.md
- documentation/market-de-sprint-81.md
- documentation/sprint-81.md
please add your activities to the release notes, thank you!
> Sprint 81 release notes

- middleware/middleware-1.3.30.md
pr to add the release note for mw 1.3.30
> release note mw 1.3.30

- README.md
- middleware/middleware-1.3.36.md
- middleware/middleware-1.3.37.md
- toc.js
release notes for german middleware version 1.3.36
> Middleware 1.3.36

- README.md
- middleware/middleware-1.3.10.md
- middleware/middleware-1.3.11.md
- middleware/middleware-1.3.39.md
- toc.js
mw 1.3.39 and its release note
> User/bri/53452 middleware 1.3.39

- portal/2022-10-05-changelong.md
add New changelog for displaying Queue description in the order/invoice page
> Changelog for displaying Queue description in orders and invoices

- portal/2022-10-18-changelog.md
Add changelog for receipt calculation
> Add changelog for receipt calculation

- portal/2022-11-08-changelog.md
> Add changelog for bulk update

- middleware/2023-01-19-1.3.42.md
> Middleware 1.3.42

- portal/2023-01-30-changelog.md
We've fixed an issue in the Receipt Journal page of the Portal that leads to filters needing to be correctly applied.
> 55478 changelog Configuration / Queue

- middleware/2023-02-15-1.3.43.md
> release note for middleware 1.3.43

- middleware/2023-03-03-1.3.44.md
> middleware 1.3.44 and its release note

- portal/2023-07-06-changelog.md
> draft for changelog

- middleware/2023-08-01-1.3.49.md
> Added release notes for MW 1.3.49

- portal/2023-08-04-changelog.md
> Published Postman collection for PosDealer API

- portal/2023-08-24-changelog.md
added a new slug and some tags, as the link at releasenotes led to the former changelog - 
fixed y copy-paste-problem 
> fixed slug for new changelog

- digital-receipt/2023-09-01-changelog.md
Release note of digital receipt - added download as PDF and minor visual improvements.
{Detail}
> Release notes digital receipt - added download as PDF

- portal/2023-08-24-changelog.md
a link in the changelog was not working
> link-repair in changelog

- middleware/2021-05-04-1.3.19.md
- middleware/2021-11-12-1.3.25.md
- middleware/2023-08-01-1.3.49.md
- middleware/2023-09-06-1.2.21103.40594.md
> fr middleware-1.2.21103.40594

- middleware/2022-10-04-1.3.40.md
> update parameter name in release note

- middleware/2024-01-18-1.3.55-rc1.md
> BYODC-1.3.55-rc1

- middleware/2024-03-18-1.3.55.md
> Release Notes 1.3.55

- middleware/2024-03-18-1.3.56.md
Included changes:
- https://github.com/fiskaltrust/middleware/pull/275
> Added changelog for Middleware 1.3.56

- middleware/2024-04-17-1.3.57.md
Included changes:
- Fixed issue in DeutscheFiskal and SwissbitCloud SCUs that prevented client registration with FCC 4.1.1
> Middleware 1.3.57

- middleware/2024-05-22-1.3.59.md
> Release notes 1.3.59

- middleware/2024-07-02-1.3.61.md
- Added support for the 32-bit version of the FCC 4.1.1
> Added release notes for MW 1.3.61

- .github/CODEOWNERS
- authors.yml
- instoreapp/2025-09-22-1.2.6.md
added instore app release notes for 1.2.6
> added instore release notes

- authors.yml
- portal/2025-09-02-changelog.md
List of items we need to add to this release notes:
> Init 2025-36 platform

- middleware/2025-09-30-1.3.77.md
This version of the Middleware is a maintenance release focusing on stability and compatibility without functional changes.
{Detail}
> Add Middleware 1.3.77 release notes
